services:
  - type: static
    name: mommate-frontend
    env: static
    buildCommand: cd front-end && npm install && npm run build
    staticPublishPath: front-end/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
